### PR TITLE
Feature/21459352 clear all filters button

### PR DESCRIPTION
**Pull request by adamtsai1**

### CODE REVIEW

**Comment by kellypacker** [comment]
@adamtsai1,

Couple of comments:

- There is a lot of duplication in the Button and ButtonSmall styled components. It's a good case for extending https://www.styled-components.com/docs/basics#extending-styles
- Seems like the button should be hidden unless there is a refinement in play. 
- Something I'm curious about is when I save RefinementClearButton Prettier removes the explicit return and changes it to implicit. Is your setup not doing that?

**Comment by adamtsai1** [comment]
@kellypacker 
- Good call, I've updated ButtonSmall to extend Button.
- I've made some updates to remove extraneous filters from searchState (e.g. if "featured" is false, it doesn't need to exist) in order to know whether filters are applied and whether the "Clear Filters" should be shown. Take a look and let me know what you think. I've also messed around a bunch to try to break it, but let me know if I've missed anything.
- Hmm my setup is not converting explicit to implicit returns and I don't see that option in my VSCode configuration. Do you see it in yours?

**Comment by kellypacker** [comment]
@adamtsai1 thanks for the changes.

- My gut is saying returning 4 things from useURLSearchState is too many things. It should probably be 2 max. Would it make sense to split that into 2 hooks?
- It would be your prettier setup that does it automatically on save. Your prettier is working in general? Which version are you on? I'm on prettier 1.17.1.

**Comment by adamtsai1** [comment]
@kellypacker In general, I think you are probably right that fewer things returned from a hook is better (though there is very little info on best practices right now since the whole concept is so new, but obviously simpler is almost always better). But I think in this case, it is going to be difficult to separate the Algolia search state from the location name since they are both updating the URL and need to be aware of each other in order to avoid making conflicting changes to the URL. The only thing I can think of (if the goal is to minimize the number of things returned from the hook) would be to move the searchLocation state up a level to MapSearch and perform transformations there before sending a manipulated searchState into the hook. That seems like a worse option to me since it is adding responsibility to MapSearch that doesn't seem to belong. Thoughts?

**Comment by kellypacker** [comment]
@adamtsai1 yeah it seems tricky to separate it. I'll merge this. Thanks!

**Pull request closed without merging**
