### PR TITLE
Feature/21441794 filters in url

### PR DESCRIPTION
**Pull request by adamtsai1**

### CODE REVIEW

**Comment by adamtsai1** [comment]
@kellypacker Actually I just noticed something weird going on. Let me take a look at it before I have you dive in here.

**Comment by adamtsai1** [comment]
@kellypacker Nevermind, good to go

**Comment by kellypacker** [comment]
@adamtsai1 I get an error when I check the featured and refresh: Warning: Failed prop type: Invalid prop `currentRefinement` of type `string` supplied to `ToggleRefinement`, expected `boolean`.

**Comment by kellypacker** [comment]
@adamtsai1 when I refresh the location filters don't reflect the state.

**Comment by adamtsai1** [comment]
@kellypacker I think this should be working now. There is one thing I am wondering about but wanted to run by you first. Since there is this search state object being passed around that has sort of become the main source of truth, I wonder if we should pass that entire object into <LocationFilters> and remove the individual states for aroundRadius, aroundLatLng, and aroundLatLngViaIP. I also have initialization code in MapSearch.js lines 29-38 that could be moved into useSearchState.js. Thoughts?

**Comment by kellypacker** [comment]
@adamtsai1 searchState is the initial state of search and configure is used to update it: https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/?language=react#dynamic-update-of-search-parameters So I think they should be separate because the location stuff is updated. 

I'm getting a little lost in everything that is happening in the hook. I'm not grasping the flow. When does the callback in the popstate get called? I couldn't seem to trigger that part. It updates the url, but also updates the search state with the bounding box. Since that's an object it probably should be using useReducer. I think things need to be separated by concern and narrowed in focus. 

I think getting the initial state from the url shouldn't happen in the hook. It should probably be passed in as a param for the initial state. Then it could be used to determine the initial state of the locations too and that wouldn't rely on the hook.

Do you get the warnings about things being called before they are declared? I get a bunch of eslint warnings/errors on the hook.

**Comment by adamtsai1** [comment]
@kellypacker Ok I've done a bunch of refactoring on useSearchState and I think it's a lot cleaner now. Take a look and let me know if you have any feedback. FYI the popstate event happens when you click "Back" on the browser. The purpose of that listener is to re-run the search on "Back", otherwise the URL changes but the search results do not get updated.

**Comment by kellypacker** [comment]
@adamtsai1 yeah I think this is looking good. It's a lot clearer. Couple thoughts:

-  I think maybe the debounce could be higher? I get a lot of states with the back button just pushing like two filters. 
- If we use _.get I think we could get all those initial states for the location down to one line as a param value. 
- A hooks convention is to start the returned function with 'set' instead of 'handle'. I think we should follow that.
- Could you add summary comment at the top of the file that summarizes what it does? 

It still feels to me like it does one too many things. 'useSearchState' doesn't indicate that is updates the url. I'm not trying to beat this to death or anything; I'm still trying to wrap my head around hooks.

**Comment by adamtsai1** [comment]
@kellypacker 

1. I increased the debounce time to 1000. Feel free to update that if you feel it needs further adjustment.
2. Good call. I added lodash.get.
3. I renamed "handle" to "set".
4. I added a brief comment to the top of the hook file.

I renamed useSearchState to useURLSearchState. That might be more appropriate considering it's really only dealing with syncing the URL with the search state. Do you have any thoughts or other ideas? And I agree, I am also still trying to get a good handle on hooks. And of course since they're so new, there are not well-established best practices out there yet.

**Comment by kellypacker** [comment]
@adamtsai1 Thanks for sticking with this! I like the rename. I would only suggest using 'setURLSearchState' instead of 'setSearchState'. 

Maybe the debounce is too much now? Now I'm not getting any back states. This part seems really tricky to get right to me.

**Comment by adamtsai1** [comment]
@kellypacker Maybe split the difference with a debounce of 750? I just pushed a change, let me know how that feels to you. I do think 1000 felt a little too long.

**Comment by kellypacker** [comment]
@adamtsai1 When select a road filter, change it and hit the back button, the url is updated, but the interface is not. Is this working for you? 

I hesitate to say it at this point, but I'm not sure incorporating the back button into the search states is very helpful with an interface like this. Just seems unnecessary because the interface allows you to change the search easily. What do you think? 

One more thing I noticed is that if I select a location to search from and then refresh the places input isn't visible. Can we populate it based on the url?

**Comment by adamtsai1** [comment]
@kellypacker I don't necessarily think it's very important to have the back functionality, but I was able to fix it pretty easily so I don't think it hurts to have.

And yeah, I noticed the location stuff this morning, so I'll work on getting that synced up with the URL. I did notice one weird thing about how it's currently working. If you start with no filters (i.e. "all" is underlined) and then click over to "a location", the underline stays under "all" until you select a location to filter by. That seems confusing to me, because to me underlined links usually indicate navigation, but in this case we are using it to indicate a filter state. I'm wondering if we should have some text or something that says "Searching within 100 miles of Richmond, VA" (perhaps with an X next to it so the user can remove it easily) and have the underline represent which "tab" the user is looking at. Hopefully that explanation makes sense. Another example of where the current setup doesn't quite work is that if you have a filter by "a location", there's no way to get back to showing "all" without manually removing it from the URL.

**Comment by adamtsai1** [comment]
Of course, if we use the links strictly as navigation, then simply clicking on "my location" or "a location" probably shouldn't automatically apply the filter. We might want the user to make an extra interaction to apply those.

**Comment by kellypacker** [comment]
@adamtsai1 yeah you are right there are a couple of wonky things there. I think you are right about disentangling the filter from the navigation. Can you take a whack at that? It's probably a separate task.

**Comment by adamtsai1** [comment]
@kellypacker Sure thing. I am going to go ahead and merge this one since the location filter stuff will all be built on top.

**Pull request merged**
