### PR TITLE
Feature/21442054 detail

### PR DESCRIPTION
**Pull request by kellypacker**
This adds a detail page for a town. I made a wrapper Map component so it could be reused outside of the Algolia-driven map. 

@adamtsai1 let me know if you have any feedback.

### CODE REVIEW

**Comment by adamtsai1** [comment]
@kellypacker It might be good to have a redirect to the home page if the user hits an undefined route (or perhaps a 404 page). We probably want to consider updating GeoSearchMapbox.js to use hooks (useEffect instead of componentDidMount/componentDidUpdate and useState for viewport).

**Comment by kellypacker** [comment]
@adamtsai1 I tried to convert that to hooks, but kept ending up with endless loops updating the viewport. So either it need to be restructured or my knowledge of hooks is lacking in this scenario. 

I did add the 404 page. Good idea. 

I'm going to marge this and think more about the hooks.

**Comment by kellypacker** [comment]
Actually I did figure it out. I used https://github.com/kentcdodds/use-deep-compare-effect to compare the hits and useReducer. Seems like a good way to do it.

**Comment by adamtsai1** [comment]
@kellypacker Looks good. I merged it into master.

**Pull request merged**
