### PR TITLE
Feature/21441796 featured filter

### PR DESCRIPTION
**Pull request by adamtsai1**
Let me know if you have any feedback.

### CODE REVIEW

**Comment by kellypacker** [comment]
@adamtsai1 I think this can be more simply done by using this widget: https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/react/

Maybe this won't be an issue after that switch is made, but when I have the featured checked and go to map and back to list and to map again, only one town is on the map: Granite. The list view has all 3.

**Comment by kellypacker** [comment]
I have a fix for the second part. It was unrelated to this.

**Comment by kellypacker** [comment]
@adamtsai1 can you style the filter text so its smaller and has a padding from the checkbox?

**Comment by adamtsai1** [comment]
@kellypacker Done. I couldn't figure out an easy way to add the margin using just the component's built-in functionality, so I set the ToggleRefinement's label prop to an empty string and added an extra span.

**Comment by kellypacker** [comment]
@adamtsai1 A more encapsulated way to do that would be to create a custom widget with a connector https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/react/?language=react#connector

That way if we had another one that was similar, we could use it too.

**Comment by adamtsai1** [comment]
@kellypacker Good call. I've restored the feature/21441796-featured-filter branch and pushed a change to it.

**Comment by kellypacker** [comment]
@adamtsai1 Looks good. Thanks.

**Pull request merged**
