### PR TITLE
Add road conditions filtering options

### PR DESCRIPTION
**Pull request by adamtsai1**

### CODE REVIEW

**Comment by kellypacker** [comment]
@adamtsai1 I wonder if this should be a select or a switch instead of checkboxes. Since there are only two options it's odd that it switches position when it's checked. The use case for this filter would be someone who doesn't have 4WD and only wants to see towns they can get to with 2WD. What do you think about a select?

**Comment by adamtsai1** [comment]
@kellypacker Yeah that makes sense to me. I just pushed a change and I'll go ahead and merge into master.

**Comment by kellypacker** [comment]
@adamtsai1 This looks good. I wonder if we need the big 'Filters' heading? Maybe just a line would work? Maybe there is a better solution. For mobile that area should be as compact as possible. What do you think about losing the 'Only' in 'Featured' and 'Condition'? Then those two could be on one line.

**Comment by adamtsai1** [comment]
@kellypacker That's fine with me. If it's just going to be those 2 filters for the foreseeable future, that should work. I think if that grows at all and we're concerned about mobile real estate, we might want to consider a collapsible section or something on mobile.

**Comment by kellypacker** [comment]
@adamtsai1 Looks like the RefinementSelect could be reusable if took the attribute as a prop. Can you update it?

**Comment by adamtsai1** [comment]
@kellypacker Oops thanks, I totally missed that. I just pushed a change to master.

**Pull request merged**
